version: '3'

services:

  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app