"""empty message

Revision ID: 2052df65bd98
Revises: f2445e0608e6
Create Date: 2023-02-15 17:05:45.011997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2052df65bd98'
down_revision = 'f2445e0608e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('title_user_uc', 'articles', ['title', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('title_user_uc', 'articles', type_='unique')
    # ### end Alembic commands ###
